schemas:
  bootstrap: 8000
  gcweb: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: libraries/theme-gcweb/assets/favicon.ico
  url: 'http://localhost:8080/sites/default/files/favicon.ico'
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: libraries/theme-gcweb/assets/sig-blk-en.png
  url: ''
  use_default: 0
region_wells:
  branding: ''
  breadcrumb: ''
  language_toggle: ''
  banner: ''
  search: ''
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  content_footer: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
table_responsive: '-1'
table: ''
